// generated by new-component script
import { defineComponent } from 'vue'

const ToolTip = defineComponent({
  name: 'SyToolTip',
  props: {},
  render () {
    return '<div>ToolTip just inited!</div>'
  }
})

export default ToolTip
